keyword: "oro"         # "" para sin filtro
tzname: "Europe/Madrid"
hours_recent: 24
to_emails:
  - "anartz2001@gmail.com"

sources:
  - name: "MARCA"
    listing: "https://www.marca.com/ultimas-noticias.html"
    homepage: "https://www.marca.com/"
    domain_prefix: "https://www.marca.com/"
    max_to_fetch: 400
  - name: "EXPANSION"
    listing: "https://www.expansion.com/economia.html?intcmp=MENUHOM24101&s_kw=economia"
    homepage: "https://www.expansion.com/"
    domain_prefix: "https://www.expansion.com/"
    max_to_fetch: 400
