keywords:
  - "oro"
  - "pies"
     # "" para sin filtro
tzname: "Europe/Madrid"
hours_recent: 24
to_emails:
  - "anartz2001@gmail.com"

sources:
  - name: "MARCA"
    url: "https://www.marca.com/"
    max_to_fetch: 400

  - name: "EXPANSION"
    url: "https://www.expansion.com/"
    max_to_fetch: 400

  - name: "MUNDO_DEPORTIVO"
    url: "https://www.mundodeportivo.com/"
    max_to_fetch: 400

