# .github/workflows/noticias.yml
name: Noticias automáticas
on:
  schedule:
      - cron: "*/5 * * * *"   # cada 5 minutos
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - name: Ejecutar recolector
        env:
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: python marca_harvester.py
