name: Noticias automáticas
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: python marca_harvester.py "Messi"
      - run: python marca_harvester.py "Alfonso"
      
        env:
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
